//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parqueadero
    {
        public int ParqueaderoID { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public int EspaciosTotal { get; set; }
        public int EspaciosOcupados { get; set; }
        public int EspaciosDisponibles { get; set; }
    }
}
